In [ ]:
#RANGE

In [1]:
range(5) ##passing only one argument


range(0, 5)

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [8]:
r=range(10)
r

range(0, 10)

In [11]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
range(10,40)

range(10, 40)

In [15]:
range(10,40,5)

range(10, 40, 5)

In [17]:
range(10,40,1,5)    #more the 3 arguments not allowed

TypeError: range expected at most 3 arguments, got 4

In [20]:
r

range(0, 10)

In [ ]:
#####  NUMPY   #####

In [21]:
import numpy as np  #np mandatary use any 'pchar'

In [22]:
np.__version__

'1.26.4'

In [23]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
## CREATING ARRAY

In [24]:
myList=[0,1,2,3,4,5]
myList

[0, 1, 2, 3, 4, 5]

In [25]:
type(myList)

list

In [ ]:
##  WE ARE CONVERTING LIST TO ARRAY

In [27]:
arr=np.array(myList)
arr

array([0, 1, 2, 3, 4, 5])

In [28]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# "np."  import function

In [29]:
np.arange(15)   #int argument

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(15.0)  #float argument

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [31]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(10,20)  #bydefalt 1st orge---will give row &2nd org -col

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(20,10)

array([], dtype=int32)

In [84]:
n1=(6,5)
n2=(6,8)
print(np.zeros(n1))  #parameter tuning

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [87]:
print(np.zeros(4,dtype=int)) #hyper parameter tuning

[0 0 0 0]


In [89]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [33]:
np.arange(40,5)   #1st org < 2nd arg

array([], dtype=int32)

In [34]:
np.arange(-40,5)

array([-40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28,
       -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15,
       -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,
        -1,   0,   1,   2,   3,   4])

In [35]:
np.arange(-40,-25)

array([-40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28,
       -27, -26])

In [36]:
rangeArray=np.arange(10,30)
rangeArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [43]:
rangeArray=np.arange(-10,30)
rangeArray

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29])

In [44]:
np.arange(10,10)

array([], dtype=int32)

In [45]:
np.arange()

TypeError: arange() requires stop to be specified.

In [46]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [48]:
print("NUMPY ZEROS")

NUMPY ZEROS


In [58]:
np.zeros(50)  ##  parameter tuning=preparing

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.zeros(s,dtype=int)     ##hyperparameter tuning (shif+tab)

NameError: name 's' is not defined

In [60]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [61]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
np.zeros((3,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
np.zeros((10,30),dtype=list)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [67]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
import random
random.rand(3,2)

AttributeError: module 'random' has no attribute 'rand'

In [74]:
np.random.rand(3,2)

array([[0.09142263, 0.61134211],
       [0.61977311, 0.96390589],
       [0.13747943, 0.40000589]])

In [75]:
np.random.rand(3)

array([0.75962833, 0.59568742, 0.39892627])

In [77]:
np.random.rand(3,5)

array([[0.79212385, 0.16164877, 0.33232188, 0.82147905, 0.75778672],
       [0.29618991, 0.23295213, 0.15904202, 0.52750369, 0.25594826],
       [0.54654842, 0.29241028, 0.39587126, 0.16373564, 0.58213935]])

In [78]:
np.random.randint(2,5)

2

In [102]:
np.random.randint(20,150)

86

In [81]:
np.random.randint(0,1)

0

In [124]:
np.random.randint(5,9)

7

In [82]:
np.random.randint(10,20, 5)

array([11, 19, 13, 11, 14])

In [83]:
np.random.randint(1,6, 4)

array([4, 4, 3, 4])

In [92]:

np.random.randint(20,40,4)


array([36, 30, 27, 35])

In [103]:
np.random.randint(20,40,(10,10))

array([[26, 20, 30, 36, 25, 38, 37, 25, 26, 39],
       [26, 34, 23, 28, 36, 23, 30, 38, 30, 36],
       [28, 23, 31, 35, 25, 36, 30, 20, 23, 37],
       [30, 24, 32, 20, 20, 35, 28, 33, 34, 29],
       [38, 31, 36, 38, 36, 29, 26, 36, 21, 27],
       [34, 24, 35, 24, 37, 30, 29, 26, 25, 30],
       [20, 35, 26, 31, 29, 24, 27, 38, 21, 34],
       [27, 26, 33, 20, 26, 28, 20, 29, 36, 38],
       [24, 38, 28, 33, 21, 25, 24, 38, 22, 37],
       [25, 27, 37, 25, 31, 24, 38, 28, 28, 26]])

In [93]:

np.random.randint(20,40,(20,40))

array([[29, 35, 20, 35, 28, 20, 20, 21, 24, 31, 33, 21, 30, 39, 25, 38,
        28, 36, 36, 30, 24, 25, 31, 32, 21, 25, 26, 23, 35, 32, 21, 31,
        35, 31, 24, 31, 23, 20, 38, 22],
       [36, 38, 27, 36, 33, 22, 37, 26, 28, 34, 39, 32, 26, 33, 35, 37,
        36, 33, 38, 29, 33, 34, 23, 34, 39, 39, 28, 20, 20, 33, 39, 21,
        29, 28, 33, 31, 35, 36, 35, 37],
       [21, 27, 20, 36, 21, 33, 22, 21, 37, 39, 32, 36, 27, 37, 27, 31,
        28, 27, 33, 28, 34, 23, 21, 21, 35, 28, 24, 39, 26, 35, 26, 34,
        24, 35, 20, 25, 27, 38, 33, 35],
       [34, 24, 23, 31, 29, 30, 39, 29, 38, 30, 30, 27, 35, 29, 22, 30,
        26, 34, 24, 37, 36, 38, 20, 26, 22, 35, 24, 24, 30, 28, 24, 33,
        38, 26, 26, 26, 39, 27, 32, 30],
       [29, 39, 29, 29, 39, 30, 38, 32, 20, 32, 22, 20, 26, 21, 38, 33,
        28, 39, 35, 37, 39, 37, 34, 38, 38, 31, 30, 25, 26, 30, 29, 29,
        36, 37, 27, 34, 34, 34, 27, 33],
       [30, 38, 39, 32, 30, 20, 38, 35, 33, 37, 28, 20, 25, 24, 27, 36,
   

In [94]:

np.random.randint(1,100,(12,20))

array([[12, 87, 84, 83, 49, 50, 17,  1, 81, 69, 70, 61,  6, 43, 56, 72,
        86, 10, 76, 39],
       [46, 29, 98, 51,  2, 21, 87, 10, 55, 89, 51, 57, 43, 12, 37, 96,
        49, 64, 50, 91],
       [46, 34, 37, 13, 10, 75, 36, 74, 38, 47, 74,  7, 16,  5, 54, 19,
        71, 73, 51, 78],
       [88, 54, 24, 93, 62, 51,  3, 53, 16, 21, 99, 10, 92, 58, 95,  2,
        19, 24, 68, 90],
       [70, 69, 16, 75, 38, 92, 76, 53, 92, 53, 67, 76, 45, 48, 84, 42,
        31, 53, 18, 67],
       [ 8, 99,  3, 40, 84, 80,  3, 84, 41, 72, 17, 75, 70, 89, 15, 72,
         7, 48, 97, 93],
       [79,  8, 52, 66, 73, 85, 29, 69, 72, 32, 73, 13, 98, 46, 67, 69,
        53, 56, 32, 28],
       [52, 10,  9, 26, 32, 82, 13, 60, 14, 61, 97, 76, 85, 71, 22, 19,
        54, 66, 39, 26],
       [61, 57, 87, 41, 96, 98, 34, 27, 63, 56, 59, 71, 31, 78, 76, 64,
         8, 34, 40, 24],
       [43, 63, 67,  8, 85, 75, 30, 33, 27, 18, 10, 65, 22, 64,  1, 25,
        71, 55, 17, 99],
       [97, 70, 72, 15,  7, 36

In [95]:

np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
np.arange(1,13).reshape(3,4)    #######

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [125]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [104]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

SLICING IN MARTIX

In [108]:
b=np.random.randint(10,20,(5,4))
b

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18],
       [14, 10, 19, 16],
       [19, 10, 11, 19]])

In [126]:
type(b)

numpy.ndarray

In [101]:
b[:]

array([[15, 10, 15, 17],
       [11, 12, 13, 18],
       [11, 12, 19, 12],
       [15, 19, 16, 17],
       [16, 10, 17, 19]])

In [127]:
b[1:3]

array([[13, 15, 10, 18],
       [16, 12, 15, 18]])

In [109]:
b[1:2]

array([[13, 15, 10, 18]])

In [110]:
b[1,2]

10

In [111]:
b

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18],
       [14, 10, 19, 16],
       [19, 10, 11, 19]])

In [129]:
b[0:3]

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18]])

In [130]:
b[0:4]

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18],
       [14, 10, 19, 16]])

In [112]:
b[1,3]

18

In [113]:
b[1,-1]

18

In [114]:
b[2,3]

18

In [115]:
b[0,-2]

15

In [116]:
b[0,2]

15

In [117]:
b[0:-2]

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18]])

In [118]:
b[-5,-4]

19

In [120]:
b

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18],
       [14, 10, 19, 16],
       [19, 10, 11, 19]])

In [122]:
b[-5,3]

10

In [131]:
b[2:3]

array([[16, 12, 15, 18]])

In [132]:
b[0:-2]

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18]])

In [133]:
np.random.randint(10,20,(4,4))

array([[19, 16, 11, 13],
       [14, 17, 12, 13],
       [12, 17, 12, 12],
       [14, 19, 16, 18]])

In [134]:
b

array([[19, 13, 15, 10],
       [13, 15, 10, 18],
       [16, 12, 15, 18],
       [14, 10, 19, 16],
       [19, 10, 11, 19]])

In [135]:
b[-4,-2]

10

In [ ]:
##   OPERATIONS

In [136]:
a=np.random.randint(10,20,10)
a

array([10, 18, 18, 19, 17, 13, 16, 18, 19, 16])

In [137]:
id(a)

1774592015312

In [138]:
arr

array([0, 1, 2, 3, 4, 5])

In [140]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [35, 48, 83, 89, 10, 92, 57,  9, 44, 12]])

In [141]:
arr

array([0, 1, 2, 3, 4, 5])

In [143]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [144]:
arr2[0:5]

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43]])

In [145]:
arr[:4]

array([0, 1, 2, 3])

In [142]:
arr2[:4]


array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37]])

In [146]:
arr2[:]

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [35, 48, 83, 89, 10, 92, 57,  9, 44, 12]])

In [147]:
arr2[0:5]

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43]])

In [151]:
arr2

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [35, 48, 83, 89, 10, 92, 57,  9, 44, 12]])

In [149]:
arr2[1,5]

6

In [150]:
arr2[1,4]

66

In [152]:
arr2[-2,5]

98

In [153]:
arr2[-4,5]

61

In [154]:
arr2[-1,-2]

44

In [156]:
arr2

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [35, 48, 83, 89, 10, 92, 57,  9, 44, 12]])

In [155]:
arr2[::-1]     #reverse the matrix

array([[35, 48, 83, 89, 10, 92, 57,  9, 44, 12],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [23, 95, 94, 76, 28, 46, 79, 11,  2,  8]])

In [157]:
arr2[::-2]

array([[35, 48, 83, 89, 10, 92, 57,  9, 44, 12],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48]])

In [158]:
arr2[::-3]

array([[35, 48, 83, 89, 10, 92, 57,  9, 44, 12],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [23, 95, 94, 76, 28, 46, 79, 11,  2,  8]])

In [159]:
arr2

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [35, 48, 83, 89, 10, 92, 57,  9, 44, 12]])

In [160]:
arr2[:-3]

array([[23, 95, 94, 76, 28, 46, 79, 11,  2,  8],
       [94, 87, 94, 34, 66,  6, 16, 17, 12, 48],
       [44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85]])

In [162]:
arr2[2:]

array([[44,  3,  5, 27, 15, 44, 34, 23, 33, 13],
       [29, 43, 87, 51, 43, 40, 53, 72, 56, 37],
       [49, 44, 95, 97, 72, 71, 73, 29, 25, 43],
       [53, 51, 42,  8, 39, 86,  0,  0, 52, 54],
       [44, 63, 49, 74,  4, 61,  7, 70, 12, 85],
       [ 9, 81, 92, 17, 95, 42, 47, 43, 91, 71],
       [84, 38, 88, 68, 68, 98, 30, 49, 18, 62],
       [35, 48, 83, 89, 10, 92, 57,  9, 44, 12]])

In [164]:
arr

array([0, 1, 2, 3, 4, 5])

In [166]:
arr.max()

5

In [167]:
arr.min()

0

In [168]:
arr.mean()

2.5

In [169]:
arr

array([0, 1, 2, 3, 4, 5])

In [178]:
arr.median()    ########


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [179]:
from numpy import *
a=array([1,2,3,4,5])
median(a)

3.0

In [177]:
##   WIYHOUT WORK ON IMPORT*CAN YOU FIND THE MEDIAN ,MODE

In [180]:
arr

array([0, 1, 2, 3, 4, 5])

In [181]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [184]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [205]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [211]:
arr.reshape(3,1)

ValueError: cannot reshape array of size 6 into shape (3,1)

In [190]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [191]:
arr.reshape(2,3,order='F') #print element with

array([[0, 2, 4],
       [1, 3, 5]])

In [192]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [193]:
arr

array([0, 1, 2, 3, 4, 5])

In [194]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
##   INDEXING

In [213]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
row=4
col=5

In [215]:
row

4

In [216]:
col

5

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[row,col]

45

In [219]:
mat[4,5]

45

In [221]:
mat[6] # defoult represent row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [222]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [225]:
mat[2:6:,2:4] #1:4

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [226]:
mat[1:6:,2:4] 

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [234]:
mat[2:3,2:3] 

array([[22]])

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat[1:6,2:4]

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [233]:
mat[1:2,2:4]

array([[12, 13]])

In [236]:
mat[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [237]:
mat[3:5,3:5]

array([[33, 34],
       [43, 44]])

In [ ]:
##  MASKING

In [238]:
mat  # called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
id(mat)

1774617161584

In [241]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [240]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [242]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [243]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [244]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [245]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [246]:
mat[mat==50]

array([50])

In [248]:
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [253]:
b=np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [258]:
c=np.linspace(0,1,5)

In [260]:
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [263]:
d=np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [264]:
e=np.ones((3,2))
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
f=np.array([1,2,3])
print("Array a:",a)